Algoritmo "SEGUNDOALGORITMO"
Var
NOME, NASCIMENTO, ATUAL, FUTURO, RESP1,RESP2 :INTEIRO
Inicio
atual<-2021
futuro<-2050

escreva("seu nome: ")
leia (NOME)

escreva("informe o ano de nascimento: ")
leia (NASCIMENTO)

RESP1<-atual-nascimento
RESP2<-futuro-nascimento

escreval("Atualmente voce possui: ", RESP1, " anos ")
escreval("no ano de 2050 voce vai ter", RESP2, " anos ")


Fimalgoritmo